baseURL = "/"
languageCode = "en-us"
title = "Johnny Lee"
theme = "minimal"
publishDir = "public/"

[params]
    author = "Johnny Lee"
    description = "Personal website"
    githubUsername = "leecjohnny"
    emailurl = "mailto:example@example.com"
    accent = "orange"
    showBorder = true
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "python", "r", "sql"]
    # path to favicon static directory
    favicon = "/images/favicon"
    copyright = "&copy; %s Johnny Lee All rights reserved."

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "envelope-o"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/leecjohnny/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://linkedin.com/in/johnny-c-lee/"
    name = "linkedin"
    weight = 3